### ISSUE TITLE
web 3.0-Alvaro Froylan Pacheco Osorio 

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Alvaro2-0#1]
[MAPA MENTAL DE LA WEB 3.0_Alvaro Froylan Pacheco Osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Alvaro2-0/files/14671856/MAPA.MENTAL.DE.LA.WEB.3.0_Alvaro.Froylan.Pacheco.Osorio.pdf)

**Comment by josealfredo79** [comment]
@Alvaro2-0 Falta la calificación...

**Comment by Alvaro2-0** [comment]
@josealfredo79  ING usted nos iba a calificar a mi y Antonia

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
